const products = [
  {
    _id: "1",
    name: "CHIMERA",
    image: "frontend/public/images/Chimera-01-XIV.jpg",
    description:
      "As a final boss of Cutter's Cry, the origins of this nightmarish combination of lion, goat, and dragon have been furiously debated. Some deem the creature a cruel jest of the gods, while others believe it the twisted creation of forbidden sorcery.",
    brand: "Final Fantasy II",
    category: "Fire",
    price: 9.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "GOLEM",
    image: "frontend/public/images/Golem-03-XIV.png",
    description:
      "Golems are magical constructs of clay or stone that have been imbued with temporary life. Ancient tomes claim that the creation of these beings is only possible when the laws of nature are weakened by the chaotic influence of an Umbral calamity.",
    brand: "Final Fantasy I",
    category: "Clay",
    price: 5.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "BASILISK",
    image: "frontend/public/images/Basilisk-28-XV.png",
    description:
      "The Green Slime, also known as the SCUM in the NES version, is an enemy in the original Final Fantasy. Since the Green Slime has an exceedingly high Defense stat, physical attacks will be useless, but a Black Mage's Blizzara or Fira can defeat a group of them with a single cast. Their attack may cause Poison, so the party should carry some Antidotes when traveling through the Marsh Cave. As with most of the Slime family of enemies, the greatest difficulty presented is conserving the player's valuable MP.",
    brand: "Final Fantasy XV",
    category: "Lightning",
    price: 8.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "NAGARANI",
    image: "frontend/public/images/Nagarani-29-XV.png",
    description:
      "Anguiform of daemon that slithers in the Crestholm Channels. She appears much like the naga, though a bed of snakes lies atop her head where her hair should be. The self-anointed queen of Crestholm has the power to turn her adversaries into stone, frogs, and worse. She’s also capable of self-destruction.",
    brand: "Final Fantasy I",
    category: "Fire",
    price: 7.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "HARPEIA",
    image: "frontend/public/images/Harpeia-04-XI.png",
    description:
      "Even the normal attacks of these monsters count as special attacks, striking multiple players within range. Furthermore, they are potent spellcasters, capable of casting enfeebling and elemental magics to hinder and harm their foes, and may even have special job abilities as well.",
    brand: "Final Fantasy XI",
    category: "Air",
    price: 12.99,
    countInStock: 7,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "DANBANIA",
    image: "frontend/public/images/Danbania-05-XII.png",
    description:
      "Is an ichthian/piranha-type enemy, and is docile until attacked. They may pop out of the sand sea when the player approaches an edge of an area. The Danbania in both sand seas have identical stats, but a Lv.10 version may appear on Ogir-Yensa and a Lv.14 one may appear on Nam-Yensa. Argyle Armlets can be rarely poached from them.",
    brand: "Final Fantasy XII",
    category: "Wind",
    price: 5.99,
    countInStock: 8,
    rating: 4.5,
    numReviews: 15,
  },
  {
    _id: "7",
    name: "DULLAHAN",
    image: "frontend/public/images/Dullahan-06-XIV.png",
    description:
      "While commonly considered to be a variety of ancient golem, the exact nature of these hulking suits of animated armor is unknown. One theory suggests that they once clad men, and that the original wearer's soul lingered on after death, doomed to spend the afterlife in a prison of steel.",
    brand: "Final Fantasy XIV",
    category: "Dark",
    price: 8.99,
    countInStock: 6,
    rating: 4.5,
    numReviews: 5,
  },
  {
    _id: "8",
    name: "MANDRAGORA",
    image: "frontend/public/images/Mandragora-07-XIV.png",
    description:
      "The enigmatic mandragora were first observed in the aftermath of the Seventh Umbral Era. It is not known whence they came, or if they even existed prior to the Calamity. There are those who insist that the diminutive seedkin are sentient, but further research is required to confirm such speculation.",
    brand: "Final Fantasy XIV",
    category: "Earth",
    price: 5.99,
    countInStock: 0,
    rating: 4,
    numReviews: 2,
  },
  {
    _id: "9",
    name: "DRAGON AEVIS",
    image: "frontend/public/images/DragonAevis-08-XIV.png",
    description:
      "Being a dragon that has lived in darkness for such a great span of time, its eyes have withered, yet its sense of touch has grown so acute that it may sense the slightest source of heat upon the air, thereby distinguishing obstacle from foe. 'Aevis' summons to mind the word for 'demon's armor' in an ancient tongue, and indeed, this wyrm's carapace is as impenetrable as the hardest steel.",
    brand: "Final Fantasy XIV",
    category: "Wind",
    price: 3.99,
    countInStock: 0,
    rating: 2,
    numReviews: 6,
  },
  {
    _id: "10",
    name: "ADAMANTHERON",
    image: "frontend/public/images/Adamantheron-09-XIII.png",
    description:
      "Similar to, yet much more powerful than the early Pantheron enemies, the Adamantheron is rather fast and wolf-like. Its low Stagger rate and relatively low HP make it a weak enemy, though in large numbers they can be annoying.",
    brand: "Final Fantasy XIII",
    category: "Ice",
    price: 5.99,
    countInStock: 0,
    rating: 4,
    numReviews: 8,
  },
];

export default products;
